LMS/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from subjects.views import*
from main.views import *
from employees.views import *
from django.conf.urls import handler403

handler403 = custom_403

urlpatterns = [
    #Level  <-> #Level
    path('login/',login_page,name='user_login'),
    path('logout/',logout_page,name='user_logout'),
    #-------------------------------------------
    path('levels/table/',levels_table),
    path('levels/edit/<int:pk>/',level_edit),
    path('levels/create/',level_create),
    path('levels/delete/<int:pk>/',level_delete),
    path('get_levels/',get_levels, name = 'levels.get_level'),
    #-------------------------------------------
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('groups/',include('groups.urls')),
    path('seasons/',include('seasons.urls')),
    path('departments/',include('departments.urls')),
    path('positions/',include('positions.urls')),
    path('employees/',include('employees.urls')),
    path('branches/',include('branches.urls')),
    path('students/',include('students.urls')),
    path('subjects/',include('subjects.urls')),
    path('rooms/',include('rooms.urls')),
    path('groups/',include('groups.urls')),
    #-------------------------------------------
    path('roles/table/',roles_table),
    path('roles/edit/<int:pk>/',role_edit),
    path('roles/create/',role_create),
    #-------------------------------------------


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

groups/urls.py
from django.urls import path , include
from .views import *


urlpatterns = [
    path('table/',groups_table),
    path('delete/<int:pk>/',group_delete),
    path('edit/<int:pk>/',group_edit),
    path('create/',group_create),
    path('timetable/',group_timetable),
    path('add_teacher/',add_teacher),
    path('add_student/<int:pk>/',student),
    path('student/delete/<int:sp>/<int:gp>/',remove_student)
]

groups/models.py
from django.db import models
from subjects.models import *
import ast
from multiselectfield import MultiSelectField
from employees.models import Employee
from branches.models import Branch
from seasons.models import Season
from rooms.models import Room
from subjects.models import Subject , Level
# Create your models here.

class Group(models.Model):
    PART_OF_DAY = [
        ('Morning','Morning'),
        ('Afternoon','Afternoon'),
        ('Evening','Evening')
    ]
    DAYS = [
        ('1','Monday'),
        ('2','Tuesday'),
        ('3','Wednesday'),
        ('4','Thursday'),
        ('5','Friday'),
        ('6','Saturday'),
    ]
    LANGUAGE_CHOICES = [
    ('English', 'English'),
    ('Spanish', 'Spanish'),
    ('French', 'French'),
    ('German', 'German'),
    ('Russian', 'Russian'),
    ('Chinese', 'Chinese'),
    ('Japanese', 'Japanese'),
    ('Korean', 'Korean'),
    ('Turkish', 'Turkish'),
    ('Arabic', 'Arabic'),
    ('Hindi', 'Hindi'),
    ('Italian', 'Italian'),
    ('Portuguese', 'Portuguese'),
    ('Dutch', 'Dutch'),
    ('Swedish', 'Swedish'),
    ('Polish', 'Polish'),
    ('Ukrainian', 'Ukrainian'),
    ('Greek', 'Greek'),
    ('Hebrew', 'Hebrew'),
    ('Persian', 'Persian'),
    ('Turkmen','Turkmen'),
]
    name = models.CharField(max_length=100)
    
    level = models.ForeignKey('subjects.Level', on_delete=models.CASCADE,related_name='groups')
    season = models.ForeignKey('seasons.Season',on_delete=models.CASCADE,related_name='groups')
    branch = models.ForeignKey('branches.Branch',on_delete=models.CASCADE,related_name='groups')
    capacity = models.IntegerField()
    language = MultiSelectField(max_length=100 , choices=LANGUAGE_CHOICES)
    part_of_day = models.CharField(max_length=100, choices=PART_OF_DAY)
    week_days = models.CharField(max_length=100)
    start_time = models.TimeField()
    end_time = models.TimeField()
    room = models.ForeignKey('rooms.Room',on_delete=models.CASCADE,related_name='groups')
    students = models.ManyToManyField('students.Student',related_name='groups')
    teacher = models.ForeignKey('employees.Employee',on_delete=models.SET_NULL,null=True,related_name='groups')
    deleted_at = models.DateTimeField(null=True,blank=True)

    def __str__(self):
        return self.name
    
    def get_days(self):
        return ast.literal_eval(self.week_days)
        
   


groups/forms.py
from typing import Any, Mapping
from django import forms
from django.core.files.base import File
from django.db.models.base import Model
from django.forms.utils import ErrorList
from .models import *
from subjects.models import *
from branches.models import *
from seasons.models import *
from rooms.models import *
from employees.models import *
from students.models import *

class GroupForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    subject = forms.ModelChoiceField(queryset=Subject.objects.filter(deleted_at = None),required=False,widget=forms.Select(attrs={'class':'form-select select2'})) 
    level = forms.ModelChoiceField(queryset=Level.objects.filter(deleted_at = None),widget=forms.Select(attrs={'class':'form-select select2'}))
    
    branch = forms.ModelChoiceField(queryset=Branch.objects.filter(deleted_at = None),widget=forms.Select(attrs={'class':'form-select select2'}))
    capacity = forms.IntegerField(widget=forms.NumberInput(attrs={'class':'form-control'}))
    language = forms.MultipleChoiceField(choices=Group.LANGUAGE_CHOICES,widget=forms.SelectMultiple(attrs={'class':'form-select select2'}))
    part_of_day = forms.ChoiceField(choices=Group.PART_OF_DAY,widget=forms.Select(attrs={'class':'form-select select2'}))
    week_days = forms.MultipleChoiceField(choices=Group.DAYS,widget=forms.SelectMultiple(attrs={'class':'form-select select2'}))
    start_time = forms.TimeField(widget=forms.TimeInput(attrs={'type':'time','class':'form-control'}))
    end_time = forms.TimeField(widget=forms.TimeInput(attrs={'type':'time','class':'form-control'}))
    room = forms.ModelChoiceField(queryset=Room.objects.filter(deleted_at = None),widget=forms.Select(attrs={'class':'form-select select2'}))
    

    class Meta:
        model = Group
        exclude = ['students' ,'season','teacher', 'deleted_at']
    def __init__(self, *args , **kwargs):
        super().__init__(*args ,**kwargs )
        field_order = ['name','subject','level','branch','language','capacity','room','part_of_day','week_days','start_time','end_time']
        self.fields = {key: self.fields[key] for key in field_order if key in self.fields}



class SearchForm(forms.Form):
    subject = forms.ModelChoiceField(required=False , queryset=Subject.objects.all(),
                                     widget=forms.Select(attrs={'class':'form-select select2' , 'onchange':'this.form.submit()'}))
    level = forms.ModelChoiceField(required=False , queryset=Level.objects.all(),
                                     widget=forms.Select(attrs={'class':'form-select select2' , 'onchange':'this.form.submit()'}))
    name = forms.CharField(required=False ,
                                     widget=forms.TextInput(attrs={'class':'form-control'}))
    part_of_day = forms.CharField(required=False ,
                                     widget=forms.Select(choices=Group.PART_OF_DAY,attrs={'class':'form-select select2' , 'onchange':'this.form.submit()'}))

groups/views.py
from django.shortcuts import render , redirect
from .forms import *
from .models import*
from django.http import HttpResponse
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from django.shortcuts import render
from django.utils import timezone
from django.core.paginator import Paginator  ,EmptyPage
# Create your views here.

def groups_table(request):
    all = Group.objects.all()
    search_form = SearchForm(request.GET or None)
    subject = request.GET.get('subject',None)
    if subject:
        all = all.filter(level__subject_id = subject )
    level = request.GET.get('level',None)
    if level:
        all = all.filter(level_id = level )

    name = request.GET.get('name',None)
    if name:
        all = all.filter(name__contains = name )

    part_of_day = request.GET.get('part_of_day',None)
    if part_of_day:
        all = all.filter(part_of_day = part_of_day )
    page_n = request.GET.get('page',1)
    p = Paginator(all , 10)
    try:
        page = p.page(page_n)
    except EmptyPage:
        page = p.page(1)

    teachers = Employee.objects.all()
    return render(request,'groups/table.html',context={'page':page , 'search_form':search_form,
                                                       'teachers':teachers})

def group_delete(request , pk):
    group = Group.objects.get(pk = pk)
    group.delete()
    return redirect('/groups/table/')

def group_edit(request,pk):
    group = Group.objects.get(pk = pk)
    form = GroupForm(instance=group)
    if request.method == 'POST':
        form = GroupForm( request.POST ,instance=group)
        if form.is_valid():
            form.save()
            return redirect('/groups/table/')
    return render(request,'groups/edit.html',context={'form':form})

def group_create(request):
    form = GroupForm()
    if request.method == 'POST':
        form = GroupForm( request.POST )
        if form.is_valid():
            group = form.save(commit=False)
            active_season = Season.objects.get(status = True)
            group.season = active_season
            group.save()
            return redirect('/groups/table/')
    return render(request,'groups/create.html',context={'form':form})

def group_timetable(request):
    rooms= Room.objects.all()
    days = [ 1 , 2 , 3 , 3 , 5 , 6 ]
    timetable = []

    morning_groups = Group.objects.filter(part_of_day = 'Morning')
    for room in rooms:
        groups = morning_groups.filter(room = room)
        group1 = groups.filter(week_days__contains = '1').first()
        group2 = groups.filter(week_days__contains = '2').first()
        group3 = groups.filter(week_days__contains = '3').first()
        group4 = groups.filter(week_days__contains = '4').first()
        group5 = groups.filter(week_days__contains = '5').first()
        group6 = groups.filter(week_days__contains = '6').first()
        timetable.append( [room.name , group1 ,group2 ,group3 , group4 , group5 , group6 ,])
    return render(request , 'groups/timetable.html' , context={'timetable':timetable})



def add_teacher(request):
    group_id = request.POST.get('group_id',None)
    emp_id = request.POST.get('emp_id',None)

    if group_id:
        group = Group.objects.get(id=group_id)
        if emp_id:
            emp = Employee.objects.get(id=emp_id)

            group.teacher = emp
            group.save()
        else:
            group.teacher = None
            group.save()

    return redirect('/groups/table/')

def student(request , pk):
    group = Group.objects.get(id = pk)
    group_students = group.students.all()
    students = Student.objects.all().exclude(groups = group)

    if request.method == 'POST':
        student_id = request.POST.get('student_id' , None)
        if student_id:
            student = Student.objects.get(id = student_id)
            group.students.add(student)
        
    return render(request,'groups/student_list.html',context={'students':group_students,
                                                              'group':group,
                                                              'all_students':students})


def remove_student(request,sp,gp):
    student = Student.objects.get(id=sp)
    group = Group.objects.get(id = gp)
    group.students.remove(student)
    return redirect(f'/groups/add_student/{group.id}/')

templates/groups/create.html
<!-- <style>
    label , button {
        margin-left: 15px !important; 
    }

    input[type="text"], .form-select, input[type="email"], input[type="date"], input[type="number"], textarea , select{
        margin: auto;
        width: 95% !important;
    }
</style> -->
{% extends "base.html" %}
{% block lms %}

<div class="content-page">
    <div class="content">

        <!-- Start Content-->
        <div class="container-fluid">

            <div class="py-3 d-flex align-items-sm-center flex-sm-row flex-column">
                <div class="flex-grow-1">
                    <h4 class="fs-18 fw-semibold m-0">Create Group</h4>
                </div>

                <div class="text-end">
                    <ol class="breadcrumb m-0 py-0">
                        <li class="breadcrumb-item"><a href="/groups/table/">Groups</a></li>
                        <li class="breadcrumb-item active">Create</li>
                    </ol>
                </div>
            </div>

            <div class="row">
                <div class="col-xl-6">
                    <div class="card ">
                        <div class="card-body">

                            <form action="" method="post" id="grouprom">
                                {% csrf_token %}
                                {{form.as_p}}
                                
                                <button type="submit" class="btn btn-outline-warning">Create</button>
                            </form>

                        </div>
                        
                    </div> <!-- end card-->
                </div> <!-- end col -->



            </div> <!-- end row -->
            
        </div> <!-- container-fluid -->

    </div> <!-- content -->

</div>
{% endblock lms %}  
{% block extra_js %}
<!-- <script>
    var capacity_p = $('#id_capacity').parent()
    capacity_p.append("<small id='emailHelp' style='float : right;' class='form-text text-muted'>5/10</small>")
</script> -->
<script>
    $(document).ready(function(){
        var capacity_p = $('#id_capacity').parent()
        capacity_p.append(`<div class="invalid-feedback" id='capacity_p'>sad</div>`)


        $('#id_room').change(function () {
            var roomID = $(this).val();

    ™
            


            if (roomID) {
                $.ajax({
                    url: "{% url 'rooms.get_room'  %}",
                    data: {'room_id':roomID},
                    dataType : 'json',
                    success: function(data) {
                        // alert(data)
                        var capacity = $('#id_capacity').val();
                        
                        // $('#grouprom').addClass('was-validated')
                        // alert(data)
                        if (capacity > data) {
                            $('#id_capacity').addClass('is-invalid')
                            $('#id_capacity').text(`${capacity}/${data}`)
                        } else{
                            $('#id_capacity').addClass('is-valid')
                            $('#id_capacity').text(`${capacity}/${data}`)                            
                        }
                    }
                });
            } else{
                $('#id_capacity_limit').detach()
            }
        });
        $('#id_capacity').change(function(){
            var capacity = $(this).val();
            var old_data = $('#capacity_p').text();
            var old_1 = old_data.split('/')[1];
            
            if (capacity > old_1) {
                if ($('#id_capacity').hasClass('is-valid')) {
                    $('#id_capacity').removeClass('is-valid')
                    $('#id_capacity').addClass('is-invalid')
                    $('#capacity_p').removeClass('valid-feedback')
                    $('#capacity_p').addClass('invalid-feedback')
                }
                $('#capacity_p').text(`${capacity}/${old_1}`)
            } else {
                if ($('#id_capacity').hasClass('is-invalid')) {
                    $('#id_capacity').removeClass('is-invalid')
                    $('#id_capacity').addClass('is-valid')
                    $('#capacity_p').removeClass('invalid-feedback')
                    $('#capacity_p').addClass('valid-feedback')
                }
                $('#capacity_p').text(`${capacity}/${old_1}`)
            };
        });


        $('#id_subject').change(function(){
            var subjectId = $(this).val();
            var levelDropdown = $('#id_level');

            if (subjectId) {
                $.ajax({
                    url: "{% url 'levels.get_level'  %}",
                    data: {'subject_id':subjectId},
                    dataType : 'json',
                    success: function(data) {
                        levelDropdown.empty();
                        levelDropdown.append('<option value="" selected disabled>Select level </option>');
                        $.each(data , function(index , item){
                            levelDropdown.append('<option value=" '+item.id + '">' + item.name + '</option>');
                        });
                    }
                });
            } else{
                levelDropdown.empty();
                levelDropdown.append('<option value="">Select level </option>');
            }
        });
    });


</script>
{% endblock extra_js %}

templates/groups/edit.html
<!-- <style>
    label , button {
        margin-left: 15px !important; 
    }

    input[type="text"], .form-select, input[type="email"], input[type="date"], input[type="number"], textarea , select{
        margin: auto;
        width: 95% !important;
    }
</style> -->
{% extends "base.html" %}
{% block lms %}

<div class="content-page">
    <div class="content">

        <!-- Start Content-->
        <div class="container-fluid">

            <div class="py-3 d-flex align-items-sm-center flex-sm-row flex-column">
                <div class="flex-grow-1">
                    <h4 class="fs-18 fw-semibold m-0">Edit Group</h4>
                </div>

                <div class="text-end">
                    <ol class="breadcrumb m-0 py-0">
                        <li class="breadcrumb-item"><a href="/groups/table/">Groups</a></li>
                        <li class="breadcrumb-item active">Edit</li>
                    </ol>
                </div>
            </div>

            <div class="row">
                <div class="col-xl-6">
                    <div class="card ">
                        <div class="card-body">

                            <form action="" method="post">
                                {% csrf_token %}
                                {{form.as_p}}
                                
                                <button type="submit" class="btn btn-outline-warning">Edit</button>
                            </form>

                        </div>
                        
                    </div> <!-- end card-->
                </div> <!-- end col -->



            </div> <!-- end row -->
            
        </div> <!-- container-fluid -->

    </div> <!-- content -->

</div>

{% endblock lms %}  

templates/groups/student_list.html
{% extends "base.html" %}

{% block lms %}
<div class="content-page">
    <div class="content">
        <div class="container-fluid">
            <div class="py-3 d-flex align-items-sm-center flex-sm-row flex-column">
                <div class="flex-grow-1">
                    <h4 class="fs-18 fw-semibold m-0">Groups Table</h4>
                </div>

                <div class="text-end">
                    <ol class="breadcrumb m-0 py-0">
                        <li class="breadcrumb-item"><a href="/groups/table/">Groups</a></li>
                        <li class="breadcrumb-item active">Table</li>
                    </ol>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <div class="d-flex align-items-center">
                        <h5 class="card-title mb-0">-</h5>
                        <div class="ms-auto">
                            <button type="button" class="btn btn-info me-1"  data-bs-toggle="modal" data-bs-target=".bs-example-modal-center"> Add Student </button>
                            
                            
                            
                        </div>
                    </div>
                </div><!-- end card header -->

                <div class="card-body">
                    
                    <div class="table-responsive">
                        <table class="table mb-0">
                            <thead>
                                <tr>
                            
                                    <th scope="col">Fullname</th>
                                    <th scope="col">Student ID</th>
                                    <th scope="col">Action</th>
                                </tr>
                            </thead>
                            <tbody class="table-group-divider">
                                {% for i in students %}
                                  <tr>
                                    <td>{{i.fullname}}</td>
                                    <td>{{i.student_ID}}</td>
                                    <td>
                                        <a href='/groups/edit/{{i.id}}/' aria-label="anchor" class="btn btn-icon btn-sm bg-primary-subtle me-1" data-bs-toggle="tooltip" data-bs-original-title="Edit">
                                            <i class="mdi mdi-eye-outline fs-14 text-primary"></i>
                                        </a>
                                        <a href='/groups/student/delete/{{i.id}}/{{group.id}}/' aria-label="anchor" class="btn btn-icon btn-sm bg-danger-subtle" data-bs-toggle="tooltip" data-bs-original-title="Delete">
                                            <i class="mdi mdi-delete fs-14 text-danger"></i>
                                        </a>
                                    </td>
                                {% endfor %}
                                
                            </tbody>
                        </table>
                       
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

<div class="modal fade bs-example-modal-center" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modal_text">Add Student to {{group.name}} </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                </button>
            </div>
            <div class="modal-body">
                <form action="" method="post">
                    {% csrf_token %}
                    <select name="student_id" id="student_id" class="form-select select2">
                        <option value="" selected>-----</option>
                        {% for i in all_students %}
                        
                          <option value="{{i.id}}">{{i.fullname}}</option>
                        {% endfor %}
                    </select>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>
{% endblock lms %}  

templates/groups/timetable.html
{% extends "base.html" %}

{% block lms %}
<style>
    table , tr , td{
        border-left: solid;
        border-color: rgba(128, 128, 128 , 0.2) ;
        
    }
    th{
        text-align: center;
    }
    td:nth-child(1){
        background-color: rgba(128, 128, 128 , 0.2);
        
    }
    tr:first-child th{
        background-color: rgba(128, 128, 128 , 0.2);
    }
</style>
<div class="content-page">
    
        <div class="container-fluid">
            <div class="py-3 d-flex align-items-sm-center flex-sm-row flex-column">
                <div class="flex-grow-1">
                    <h4 class="fs-18 fw-semibold m-0">Groups Timetable</h4>
                </div>

                <div class="text-end">
                    <ol class="breadcrumb m-0 py-0">
                        <li class="breadcrumb-item"><a href="/groups/table/">Groups</a></li>
                        <li class="breadcrumb-item active">Timetable</li>
                    </ol>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <div class="d-flex align-items-center">
                        <h5 class="card-title mb-0">-</h5>
                        
                    </div>
                </div><!-- end card header -->

                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table mb-0">
                            <thead>
                                <tr>
                            
                                    <th scope="col">Room</th>
                                    <th scope="col" class="mb-1 text-warning fs-14">Monday</th>
                                    <th scope="col" class="mb-1 text-warning fs-14">Tuesday</th>
                                    <th scope="col" class="mb-1 text-warning fs-14">Wednesday</th>
                                    <th scope="col" class="mb-1 text-warning fs-14">Thursday</th>
                                    <th scope="col" class="mb-1 text-warning fs-14">Friday</th>
                                    <th scope="col" class="mb-1 text-warning fs-14">Saturday</th>
                                </tr>
                            </thead>
                            <tbody class="table-group-divider">
                                {% for room in timetable %}
                                    <tr>
                                        <td>{{room.0}}</td>
                                        {% for data in room  %}
                                          {% if forloop.counter != 1 %}
                                                {% if data %}
                                                    <td>
                                                        <p style="text-align: center;"><span class="badge text-bg-info">{{ data.start_time|time:"H:i" }}-{{ data.end_time|time:"H:i" }}</span></p>
                                                        <p style="text-align: center;"><span class="mb-8 text-primary fs-14">{{data.name}}</span></p>
                                                        <p style="text-align: center;">Students:<span class="mb-8 text-primary fs-14"> {{data.students.count}} / {{data.capacity}}</span></p>
                                                        
                                                        <p style="width: 200px;">Teacher: <span class="mb-8 text-info">{{data.teacher}}</span> <a href='/groups/edit/{{data.id}}/' aria-label="anchor" class="btn btn-icon btn-sm bg-primary-subtle me-1" data-bs-toggle="tooltip" data-bs-original-title="Edit">
                                                            <i class="mdi mdi-pencil-outline fs-14 text-primary"></i>
                                                        </a></p>
                                                        
                                                    </td>
                                                {% else %}
                                                <td>-</td>
                                                {% endif %}
                                          {% endif %}
                                        {% endfor %}
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    
</div>
{% endblock lms %}  